### ISSUE TITLE
version 0.1.0 target

### ISSUE THREAD

**Issue by glensc** [smarty-gettext/tsmarty2c#1]
rewrite tsmarty2c to something maintainable.
(originally in https://github.com/smarty-gettext/smarty-gettext/pull/18)

- [x] use [Symfony\Console](http://symfony.com/doc/current/components/console.html) for CLI application
- [x] use [Symfony\Finder](http://symfony.com/doc/current/components/finder.html) to find files
- [x] parse template using Smarty engine into tokens: #2
- [x] process smarty tokens into "Tag" object: #3
- [x] for each "Tag" object, use some library from [Packagist](https://packagist.org/) to write `.po` files: #4:
  - [geekwright/po](https://github.com/geekwright/Po)
  - [sepia/po-parser](https://github.com/raulferras/PHP-po-parser)
  - <del>[maxakawizard/po-parser](https://github.com/MAXakaWIZARD/PoParser)</del> write interface is only via arrays
  - [gettext/gettext](https://github.com/oscarotero/Gettext)

**Comment by glensc** [comment]
(originally in https://github.com/smarty-gettext/smarty-gettext/pull/18#issuecomment-300617949)

[geekwright/po](https://github.com/geekwright/Po) - looks like it already has smarty parser: https://github.com/geekwright/Po/blob/master/src/PoInitSmarty.php

it uses [$smarty->getTags](http://www.smarty.net/docs/en/api.get.tags.tpl), but that returns just tag, and tag attributes, what's between the attribute is not known. `{t arg=1}text{/t}` <- `text` is not returned by that method.

**Comment by petski** [comment]
> use some library from Packagist to write .po files

Have you seen https://github.com/oscarotero/Gettext ?

**Comment by petski** [comment]
FWIW: because this project isn't finished yet, I currently use this work-around:
```
$smarty->clearCompiledTemplate();
$smarty->compileAllTemplates('.html', true);
```
Then I do something like this on the shell to get my .po(t) file:
`xgettext --output=/tmp/smarty.pot ... --language=PHP $smarty->getCompileDir() . '/*.html.php';`

This approach actually works quite good. Unfortunately, the comment for each msgid references a line in the compiled template instead of the actual template. (Which isn't an issue for me at this moment).

If the latter would be an issue for the end-user, there might be a way to hook into the smarty compiler and keep track of a compiled_file -> template_file map.

**Comment by glensc** [comment]
i have full cycle working with `geekwright/po` here locally, just haven't got around naming classes properly, so not published :)

for smarty parser, it's commited, waiting for #2 to be merged.

i'll check https://github.com/oscarotero/Gettext

**Comment by glensc** [comment]
[0.1.0](https://github.com/smarty-gettext/tsmarty2c/releases/tag/0.1.0) has been released.

providing `.phar` and more features can come later! :)
